[package]
name = "space-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "space-client"
path = "src/main.rs"

[build-dependencies]
cc.workspace = true

[dependencies]
space-client-core.workspace = true
space-config.workspace = true
contracts.workspace = true
tracing.workspace = true
tokio = { workspace = true }
